Portal_Empreendedor/Portal_Empreendedor/Controllers/IdeiasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortalEmpreendedor.Controllers
{
    public class IdeiasController : Controller
    {
        //
        // GET: /Ideias/
        public ActionResult Index()
        {
            return View();
        }
	}
}

Portal_Empreendedor/Portal_Empreendedor/Controllers/PerfilEmpreendedorController.cs
using Portal_Empreendedor.Entidades;
using Portal_Empreendedor.Models;
using PortalEmpreendedor.Util;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortalEmpreendedor.Controllers
{
    public class PerfilEmpreendedorController : Controller
    {
        private DB_PORTAL_EMPREENDEDORContext banco;
        private empreendedor perfil;

        public  PerfilEmpreendedorController()
        {
            this.banco = new DB_PORTAL_EMPREENDEDORContext();
            this.perfil = new empreendedor();
        }

        //
        // GET: /PerfilEmpreendedor/
        public ActionResult Index(string empreendedor)
        {
            if (empreendedor == null)
            {
                return RedirectToAction("Login", "Acesso");
            }

            string idString = Cripitografia.Descriptografar(empreendedor);
            int id = Convert.ToInt32(idString);
            var dadosEmpreendedor = buscaDadosEmpreendedor(id);

            if (dadosEmpreendedor == null)
            {
                return Content("Item not found");
            }

            return View(dadosEmpreendedor);
        }

        private empreendedor buscaDadosEmpreendedor(int id)
        {
            this.perfil = banco.empreendedors.FirstOrDefault(x => x.id == id);

            if (this.perfil == null)
            {
                return null;
            }
            return this.perfil;
        }

	}
}

Portal_Empreendedor/Portal_Empreendedor/Views/Ideias/Index.cshtml
@{
    ViewBag.Title = "Ideias";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <br /><br /><br />
    <div class="row">
        <div class="col-md-12">
            <h1 class="page-header text-center" style="font-family: Aharoni; color: cadetblue">Mural de Ideias</h1>

            <div>
                <form action="/" method="post">
                    <label class="control-label">Filtrar Ideia por nome:</label>
                    <input type="text" name="nome" value="" class="form-control" placeholder="exe.: tecnologia móvel" />
                    <button type="submit" class="btn btn-group-sm btn-primary btn-block">Buscar</button>
                </form>
            </div>

            <!-- foreach para apresentar as ideias -->
            <h3 style="color: darkseagreen">Título da Ideia</h3>
            <p class="lead">
                por @Html.ActionLink("Autor", "Index", "PerfilEmpreendedor", null, null)
            </p>
            <p><span class="glyphicon glyphicon-time"></span> Postado em 27 de Agosto de 2015</p>

            <blockquote>
                <p class="blockquote">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, veritatis, tempora, necessitatibus inventore nisi quam quia repellat ut tempore laborum possimus eum dicta id animi corrupti debitis ipsum officiis rerum.</p>
            </blockquote>

            <hr>

            <h3 style="color: darkseagreen">Título da Ideia</h3>
            <p class="lead">
                por @Html.ActionLink("Autor", "Index", "PerfilEmpreendedor", null, null)
            </p>
            <p><span class="glyphicon glyphicon-time"></span> Postado em 27 de Agosto de 2015</p>

            <blockquote>
                <p class="blockquote">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, veritatis, tempora, necessitatibus inventore nisi quam quia repellat ut tempore laborum possimus eum dicta id animi corrupti debitis ipsum officiis rerum.</p>
            </blockquote>

            <hr>

            <h3 style="color: darkseagreen">Título da Ideia</h3>
            <p class="lead">
                por @Html.ActionLink("Autor", "Index", "PerfilEmpreendedor", null, null)
            </p>
            <p><span class="glyphicon glyphicon-time"></span> Postado em 27 de Agosto de 2015</p>

            <blockquote>
                <p class="blockquote">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, veritatis, tempora, necessitatibus inventore nisi quam quia repellat ut tempore laborum possimus eum dicta id animi corrupti debitis ipsum officiis rerum.</p>
            </blockquote>

            <hr>

            <!-- Pager -->
            <ul class="pager">
                <li class="previous">
                    <a href="#">← Antigas</a>
                </li>
                <li class="next">
                    <a href="#">Novas →</a>
                </li>
            </ul>
        </div>
    </div>
</div>

<script type="text/javascript">
    document.getElementById("servico").style.display = 'none';
    document.getElementById("contato").style.display = 'none';
</script>