Portal_Empreendedor/Portal_Empreendedor/Controllers/AcessoController.cs
using Portal_Empreendedor.Entidades;
using Portal_Empreendedor.Models;
using PortalEmpreendedor.Util;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Portal_Empreendedor.Controllers
{
    public class AcessoController : Controller
    {
        private DB_PORTAL_EMPREENDEDORContext banco;
        private Perfil_Empreendedor perfilEmpreendedor;
        private Perfil_Investidor perfilInvestidor;

        public AcessoController()
        {
            banco = new DB_PORTAL_EMPREENDEDORContext();
        }
        //
        // GET: /Acesso/
        public ActionResult Login()
        {
            return View();
        }



        [AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult Login(acesso acesso)
        {

            if (string.IsNullOrEmpty(acesso.email))
                ModelState.AddModelError("usuario", "Campo e-mail obrigatório!");
            if (string.IsNullOrEmpty(acesso.senha))
                ModelState.AddModelError("senha", "Campo senha obrigatório!");
            if (!ModelState.IsValid)
                return View(acesso);

            var empreendedor = banco.empreendedors.FirstOrDefault(x => x.email.ToLower().Equals(acesso.email.ToLower()));
            var investidor = banco.investidors.FirstOrDefault(x => x.email.ToLower().Equals(acesso.email.ToLower()));

            if (empreendedor == null && investidor == null)
            {
                ModelState.AddModelError("", "Usuário não encontrado");
                return View(acesso);
            }

            var senhaCript = Cripitografia.Criptografar(acesso.senha);

            if (empreendedor != null)
            {
                var senhaEmpreendedor = banco.acessoes.Any(x => x.email == empreendedor.email && x.senha == senhaCript);

                if (senhaEmpreendedor)
                {
                    string id = Cripitografia.Criptografar(Convert.ToString(empreendedor.id));

                    return RedirectToAction("Index", "PerfilEmpreendedor", new { empreendedor = id });
                }
                else
                {
                    ModelState.AddModelError("", "Senha Incorreta");
                    return View(acesso);
                }

            }
            else
            {
                var senhaInvestidor = banco.acessoes.Any(x => x.email == investidor.email && x.senha == senhaCript);

                if (senhaInvestidor)
                {
                    string id = Cripitografia.Criptografar(Convert.ToString(investidor.id));
                    return RedirectToAction("Index", "PerfilInvestidor", new { investidor = id });
                }
                else
                {
                    ModelState.AddModelError("", "Senha Incorreta");
                    return View(acesso);
                }


            }

        }
    }
}

Portal_Empreendedor/Portal_Empreendedor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - Portal do Empreendedor</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- Custom Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="modalMain"></div>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation" style="background-color: #fff">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a id="inicio" class="navbar-brand topnav" href="~/Home/Index">Portal do Empreendedor</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @Html.ActionLink("Login", "Login", "Acesso", null, new {id="login" })
                    </li>
                    <li>
                        @Ajax.ActionLink("Cadastrar", "modalTipoCadastro", "Home", new { id = "cadastro"}, new AjaxOptions { HttpMethod = "get", UpdateTargetId = "modalMain", OnSuccess = "$('#modalTipoCadastro').modal('show');" })
                    </li>
                    <li>
                        @Html.ActionLink("Ideias", "Index", "Ideias", null, new { id = "ideias" })
                    </li>
                    <li>
                        <a href="#services" id="servicos">Serviços</a>
                    </li>
                    <li>
                        <a href="#contact" id="contato">Contato</a>
                    </li>
                    <li>
                        @Html.ActionLink("Sair", "Index", "Home", null, new { id = "sair" })
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <div class="conteudo">
        @RenderBody()
        <hr />
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <p class="copyright text-muted small text-center">&copy; @DateTime.Now.Year All Rights Reserved</p>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)




    <script type="text/javascript">

        $(function () {
            $('a').bind('click', function (event) {
                var $anchor = $(this);
                $('html, body').stop().animate({ scrollTop: $($anchor.attr('href')).offset().top }, 1000, 'easeInOutExpo');
            });
        });

        jQuery(document).ready(function ($) {
            $.easing.easeInOutExpo = function (x, t, b, c, d) { // definição do efeito que será posteriormente usado no animate
                if (t == 0) return b;
                if (t == d) return b + c;
                if ((t /= d / 2) < 1) return c / 2 * Math.pow(2, 10 * (t - 1)) + b;
                return c / 2 * (-Math.pow(2, -10 * --t) + 2) + b;
            }

            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({
                    scrollTop: $(this.hash).offset().top
                }, {
                    duration: 3000,
                    easing: 'easeInOutExpo' // basta usar o mesmo nome que você definiu acima ;)
                });
            });
        });

        //Ajax na unha!
        @*$(function () {
            $("#btnCadastrar").on("click", function () {
                $.ajax({
                    url: "/Home/modalTipoCadastro",
                    method: "get",
                    success: function (data) {
                        $("#modalMain").html(data);
                        $("#modalTipoCadastro").modal("show");
                    }
                })

            })

        })*@
    </script>
</body>
</html>

Portal_Empreendedor/Portal_Empreendedor/Views/Shared/_Layout_Login_Cadastros.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - Portal do Empreendedor</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- Custom Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="modalMain"></div>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand topnav" href="~/Home/Index">Portal do Empreendedor</a>
            </div>
        </div>
        <!-- /.container -->
    </nav>
    
    <div class="conteudo">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script type="text/javascript">

        $(function () {
            $('a').bind('click', function (event) {
                var $anchor = $(this);
                $('html, body').stop().animate({ scrollTop: $($anchor.attr('href')).offset().top }, 1000, 'easeInOutExpo');
            });
        });

        jQuery(document).ready(function ($) {
            $.easing.easeInOutExpo = function (x, t, b, c, d) { // definição do efeito que será posteriormente usado no animate
                if (t == 0) return b;
                if (t == d) return b + c;
                if ((t /= d / 2) < 1) return c / 2 * Math.pow(2, 10 * (t - 1)) + b;
                return c / 2 * (-Math.pow(2, -10 * --t) + 2) + b;
            }

            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({
                    scrollTop: $(this.hash).offset().top
                }, {
                    duration: 3000,
                    easing: 'easeInOutExpo' // basta usar o mesmo nome que você definiu acima ;)
                });
            });
        });

        //Ajax na unha!
        @*$(function () { 
            $("#btnCadastrar").on("click", function () {
                $.ajax({
                    url: "/Home/modalTipoCadastro",
                    method: "get",
                    success: function (data) {
                        $("#modalMain").html(data);
                        $("#modalTipoCadastro").modal("show");
                    }
                })

            })

        })*@
    </script>
</body>
</html>